site_name: dbcontroller
site_url: https://hlop3z.github.io/dbcontroller
repo_url: https://github.com/hlop3z/dbcontroller
copyright: Copyright © Hlop3z

theme:
  name: material
  locale: en
  features:
    - navigation.tabs
  icon:
    logo: material/database-cog
  palette:
    primary: light blue

nav:
  - Home: index.md
  - SQL: sql.md
  - Mongo: mongo.md
  - Extras:
      - SQL-Where: sql-where.md
      - SQL-Search: sql-search.md
      - ID-Decode: id-decoder.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
